version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: gym_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: gymdb
      POSTGRES_USER: gymuser
      POSTGRES_PASSWORD: gympassword
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: